var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/dashboard/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__002m6ib._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0krgytt.js")
R.c("server/chunks/ssr/_0h~d50d._.js")
R.c("server/chunks/ssr/node_modules_next_dist_09jzzl8._.js")
R.c("server/chunks/ssr/[root-of-the-server]__01iyy0g._.js")
R.c("server/chunks/ssr/[root-of-the-server]__090jxzh._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0efrvl6._.js")
R.c("server/chunks/ssr/src_app_loading_tsx_00w_nei._.js")
R.c("server/chunks/ssr/_02tmamc._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0ee1czk._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_dashboard_page_actions_0lwvh3z.js")
R.m(889)
module.exports=R.m(889).exports
